import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const links = [
  { name: "Main", url: "/" },
  { name: "JS", url: "/js" },
  { name: "DSA", url: "/dsa" },
];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${inter.className}`}>
      <body className="min-h-screen bg-zinc-950 text-zinc-200 antialiased">
        <header className="mx-2 flex border-b border-b-zinc-700 px-8 py-4">
          <ul className="flex gap-4">
            {links.map((link) => (
              <li key={link.name}>
                <Link href={link.url}>{link.name}</Link>
              </li>
            ))}
          </ul>
        </header>
        {children}
      </body>
    </html>
  );
}
